FROM ubuntu:latest

RUN apt-get update && apt-get install -y nodejs npm

WORKDIR /communityfund-contract

RUN rm -rf ./*

COPY package*.json /communityfund-contract

RUN npm install

COPY src /communityfund-contract/src/

RUN npm run buildLinux
